---
title: "Final Project Analysis"
author: "Charles Yang, Isaac Tegeler, Carter Wunsch, Bennet Brosseau, Nicholas Heger"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

# Data was stored in CSV (Comma Delimited), but was tab delimited.
data <- read.table("VIQT_data.csv", sep="\t", header=TRUE)
```

# Exploratory Analysis
### Charles S1-6, education v. Full Score
```{r}
data %>%
  group_by(S1) %>%
  summarise(`Full Score`=mean(score_full), .groups="drop") %>%
  filter(S1 > 0) %>%
  ggplot(aes(x=S1, y=`Full Score`)) +
  geom_bar(stat="identity", width=.7) +
  ggtitle("Mean Full Scores by S1 Response")
```

```{r}
data %>%
  group_by(S2) %>%
  summarise(`Full Score`=mean(score_full), .groups="drop") %>%
  filter(S2 > 0) %>%
  ggplot(aes(x=S2, y=`Full Score`)) +
  geom_bar(stat="identity", width=.7) +
  ggtitle("Mean Full Scores by S2 Response")
```

```{r}
data %>%
  group_by(S3) %>%
  summarise(`Full Score`=mean(score_full), .groups="drop") %>%
  filter(S3 > 0) %>%
  ggplot(aes(x=S3, y=`Full Score`)) +
  geom_bar(stat="identity", width=.7) +
  ggtitle("Mean Full Scores by S3 Response")
```

```{r}
data %>%
  group_by(S4) %>%
  summarise(`Full Score`=mean(score_full), .groups="drop") %>%
  filter(S4 > 0) %>%
  ggplot(aes(x=S4, y=`Full Score`)) +
  geom_bar(stat="identity", width=.7) +
  ggtitle("Mean Full Scores by S4 Response")
```

```{r}
data %>%
  group_by(S5) %>%
  summarise(`Full Score`=mean(score_full), .groups="drop") %>%
  filter(S5 > 0) %>%
  ggplot(aes(x=S5, y=`Full Score`)) +
  geom_bar(stat="identity", width=.7) +
  ggtitle("Mean Full Scores by S5 Response")

```

```{r}
data %>%
  group_by(S6) %>%
  summarise(`Full Score`=mean(score_full), .groups="drop") %>%
  filter(S6 > 0) %>%
  ggplot(aes(x=S6, y=`Full Score`)) +
  geom_bar(stat="identity", width=.7) +
  ggtitle("Mean Full Scores by S6 Response")
```

```{r}
data$education <- recode(data$education, `1`="< HS", `2`="HS", `3`="UNI", `4`="GRAD") %>% factor(levels=c("< HS", "HS", "UNI", "GRAD"))
data %>%
  group_by(education) %>%
  summarise(`Full Score`=mean(score_full), .groups="drop") %>%
  ggplot(aes(x=education, y=`Full Score`)) +
  geom_bar(stat="identity", width=.7) +
  ggtitle("Mean Full Scores by Education")
```

### Isaac S7 - 12, urban v. Full Score
```{r}

```

### Nicholas S13 - 18, gender v. Full Score
```{r}

```

### Carter S19 - 24, engnat v. Full Score
```{r}

```

### Bennet S25-30, age v. Full Score
```{r}

```

